name: example_proxy
description: Arcane Voice example proxy server.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: ^3.11.0

dependencies:
  arcane_voice_proxy:
    path: ../arcane_voice_proxy
  arcane_voice_models:
    path: ../arcane_voice_models

dev_dependencies:
  http: ^1.2.2
  lints: ^6.0.0
  test: ^1.25.6
